POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username":"Flippy",
    "password":"password",
    "email":"flipflipflipflip19@gmail.com",
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    //dataobj
}

###
